FROM deepmind/kapitan

LABEL "com.github.actions.name"="compile"
LABEL "com.github.actions.description"="Runs Kapitan compile"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="purple"

LABEL "repository"="http://github.com/ademaria/kapitan-github-action.git"
LABEL "homepage"="http://github.com/actions"
LABEL "maintainer"="Alessandro De Maria <alessandro.demaria@gmail.com>"
